### PR TITLE
Work on removing ESP8266HTTPClient for regular client

### PR DESCRIPTION
**Pull request by witnessmenow**
Steve, don't merge yet! Still a WIP

- Need to sort out IP address versus regular URL

- Need to add examples

### CODE REVIEW

**Comment by chunkysteveo** [comment]
Great updates Brian, very informative and worthwhile implementing at this stage and switching to the standard clients. Like the debug flags too - saves me un-commenting and commenting as I release updates!

Agree point about IP - I connect to my printer locally, and when at work, so it uses a host name and custom port - so the host will need to be able to be either an IP address, or string host name.

**Comment by witnessmenow** [comment]
Have updated the PR @chunkysteveo , probably still needs some work though (need to fix the other example for the ESP8266, and need to add that same example for ESP32)

I have put in a solution for using a URL or an IP address, I'm not sure if there is any other way around this, maybe there is a way to convert the string into an IP address, I'm not too sure. **Note:** I have not tested the URL way as I don't have Url setup for my Octoprint server. (I have tested that it fails to connect :) )

Here is the basic example running on an ESP32, I've added that example into the PR too
octoprintesp32

**Comment by chunkysteveo** [comment]
Many thanks Brian. Will take a look in the morning and merge. I can test the url version. I am sure i saw a script that split an IP string into IP, I may look around too.

Thanks again. 

Steve

**Review by chunkysteveo — COMMENTED** [review]
Isn't "IPAddress" an ESP8266 only class?

**Comment by witnessmenow** [comment]
As far as I know its a generic arduino class, same as client. It worked OK
for me on the esp32 and you see it in examples using the Ethernet shield too

**Comment by chunkysteveo** [comment]
OK great. I did look up some examples of converting an IP String to an IP address and checking this with "fromString", but people have said this expands your source so much it won't fit on an UNO using the String class. I think your solution of having two checks to see if it connects with IP and then host works well! :)

**Comment by witnessmenow** [comment]
Cool!

I'll try get am example of the uno added this week, Wednesday is "date
night" for us so strictly no arduino stuff allowed , so it won't be today!

I do have my doubts about it running on an uno (the memory required for
arduino json is quite high) but we'll see!

**Comment by chunkysteveo** [comment]
ppfftt... date night, what is it - some kind of special "love day"??!  ...oh wait!!

I was looking to buy one of the Ethernet boards (not a shield) to add to an UNO to see how well it worked, if at all. After getting an issue raised about connecting in a secure network (University), I did think about possible industrial and commercial uses where WiFi is a no-go, so Ethernet may be pretty useful to some... may be...!? But like you said - UNO is limited, but there may be other Arduino boards that work well, such as a MEGA and LAN port.

That would be cool though if you have an UNO and Ethernet. Thumbs up!

I will add in these changes, thanks!

**Pull request merged**
