### PR TITLE
Feature/status target temps

### PR DESCRIPTION
**Pull request by anfichtn**
Added target temperatures to PrinterStats

### CODE REVIEW

**Comment by chunkysteveo** [comment]
Looks good to me. I wasn't sure if targets were of use to people, so left them out. Happy to have them in! I should really pull in all useful elements from the Json eventually!!!

**Comment by anfichtn** [comment]
I created an little sketch for my ambient light with WS2812B and ESP8622. For displaying the heating progress the targets are needed.

**Comment by chunkysteveo** [comment]
Ahh! That is so cool! Glad you used the library!

**Comment by chunkysteveo** [comment]
And thanks for the PR. Will add you to the contributors on the next release!

**Comment by anfichtn** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I forgot to add the Image :-)

Stephen Ludgate <notifications@github.com> schrieb am 11.11.2018:
>And thanks for the PR. Will add you to the contributors on the next
>release!
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQFCBAEBCgAsBQJb7EZEJRxBLiBGaWNodG5lciA8bXVzdGVybWF4NTU2QGdtYWls
LmNvbT4ACgkQiMTzmaSYplfXrAgAgUzoFarCC51GoKkjoU5tsnJz2T4J4OmjagGR
xpZzA8FsWdif0KFY6CBNSEl8dSBaZhKM4ehY7BdHJ5MPjZe6eIjltDhW7S6UTKjM
M/QW24N5o6k6nRgco6Iryy67jDzrAwybPBDV2YPL6/s4REPDWJ2WdJw4ea54n2Zi
vmMIMnOPlnxeVwElNh7arMlTwvXrHlaUW4ZWBNZ0NsEviz6x/lWIWONAGOZO+SQc
14IMM9C00pUOxmGsjuOV9ioWVKOdF4+H/ZklN/vCl1+/al/bFdLtjYFeJgfcPM3e
AElCtfY3q1uEFzcUrJXNGDO4kRmj/ffpSPxHqBlE7ehfqh8Oow==
=SAhO
-----END PGP SIGNATURE-----

**Comment by chunkysteveo** [comment]
There's no image buddy?

**Pull request merged**
